### ISSUE TITLE
Comments should not be editable

### ISSUE THREAD

**Issue by staion16** [ipranjal/the-wire-pro#4]
TheWire posts are not editable but the comments you implemented are. I think the comments should't be editable as well. Or maybe make an option to permit editing both or not at all.

**Comment by staion16** [comment]
Also, comments are not restricted by how many characters they support like thewire posts are.

**Comment by ipranjal** [comment]
@staion16 

It’s been a while , but I am sure this plug-in now uses a elgg’s own comment system so this should not be a issue anymore
